#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by the remote unit leaving the relationship.
# This script should be idempotent.
#raw
juju-log $JUJU_REMOTE_UNIT departed
#end raw
