#!/usr/bin/env python

import os
import random
import string
import subprocess
import urllib

import MySQLdb

change_type = os.environ.get("ENSEMBLE_CHANGE")

def on_join():

    # Connect to mysql
    passwd = open("/var/lib/ensemble/mysql.passwd").read().strip()
    print passwd
    connection = MySQLdb.connect(user="root", host="localhost", passwd=passwd)

    cursor = connection.cursor()

    # Find existing databases
    cursor.execute("show databases")
    databases = [i[0] for i in cursor.fetchall()]

    change_unit = os.environ.get("ENSEMBLE_REMOTE_UNIT")
    service, _ = change_unit.split("/")

    # We'll name the database the same as the service.
    database_name = service

    # Determine if we need to create a new database
    if database_name in databases:
        return

    # Create new database
    cursor.execute(
        "create database %s character set utf8" % database_name)

    # Create database user and grant access
    service_password = "".join(random.sample(string.letters, 10))
    cursor.execute(
        "grant all on %s.* to %s identified by '%s'" % (
            database_name,
            service,
            service_password))

    cursor.execute("flush privileges")

    cursor.close()
    connection.close()

    hostname = urllib.urlopen(
        "http://169.254.169.254/latest/meta-data/local-hostname").read()

    print "setting values"
    print "host", hostname
    print "database", database_name
    print "user", service
    print "password", service_password

    # Store new values in relation settings.
    p = subprocess.Popen(
        ["relation-set",
         "mysql/0",
         "database=%s" % database_name,
         "user=%s" % service,
         "password=%s" % service_password,
         'host=%s' % hostname,],
        close_fds = True)

    os.waitpid(p.pid, 0)

if change_type == "joined":
    on_join()
