#!/bin/bash

PASSWORD="FOOBAR"

sudo apt-get install -qqy debconf-utils

echo mysql-server-5.1 mysql-server/root_password password $PASSWORD | debconf-set-selections
echo mysql-server-5.1 mysql-server/root_password_again password $PASSWORD | debconf-set-selections

DEBIAN_FRONTEND=noninteractive apt-get -y install -qq mysql-server