#!/bin/bash

set -e

DEBIAN_FRONTEND=noninteractive apt-get -y install -qq haproxy

cat > /etc/default/haproxy <<EOF
ENABLED=1
EOF
# We actually want it stopped until at least one thing has joined
service haproxy stop
