.TH charm 1 2011-09-23 charm-tools
.\"
.SH NAME
charm \- Call a charm-tools script
.\"
.SH SYNOPSIS
.B charm
[\fI script_name [\fI args \fR]... \fR]
.\"
.SH DESCRIPTION
.PP
.B charm
runs
.B script_name
from charm-tools. If no script_name is specified, lists the available scripts.
All of the 
.B args
are passed to the underlying script.
.\"
.SH AUTHOR
Written by Clint Byrum
.RB < clint@ubuntu.com >
.\"
.SH BUGS
Report bugs at 
.RB < https://github.com/juju/charm-tools/issues >
.\"
.SH COPYRIGHT
Copyright \(co 2011-2019 Canonical Ltd.
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
