#!/bin/bash

set -e

DEBIAN_FRONTEND=noninteractive apt-get -y install -qq memcached

cat > /etc/default/memcached <<EOF
ENABLE_MEMCACHED=yes
EOF
cat > /etc/memcached.conf <<EOF
-p 11211
-u nobody
-l 0.0.0.0
-c 1024
-d
-m 1500
EOF
invoke-rc.d memcached stop || true
invoke-rc.d memcached start || true
