#!/usr/bin/php
<?php
if (file_exists('/etc/mediawiki/LocalSettings.php') 
    && file_exists('/etc/mediawiki/slaves.data'))
{
    require('LocalSettings.php');
    $dbservers = array( array('host'=>$wgDBserver,
          'dbname'=>$wgDBname,
          'user'=>$wgDBuser,
          'password'=>$wgDBpassword,
          'type'=>$wgDBtype) );
    $arr = unserialize(file_get_contents('/etc/mediawiki/slaves.data'));
    $total_dbservers = array_merge($dbservers, $arr);
    $content = '<?php $wgDBservers = '.var_export($total_dbservers, TRUE);
} else {
    $content = '<?php $wgDBservers = FALSE';
}

file_put_contents('/etc/mediawiki/dbservers.php', $content);
