#!/bin/bash

DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends -y -q install mediawiki php5-cli postfix python-mysqldb

# a bit hacky -- makes sure its there even if memcached is never related
touch /etc/mediawiki/memcached_settings.php
chmod 0644 /etc/mediawiki/memcached_settings.php
touch /etc/mediawiki/dbservers.php
chmod 0644 /etc/mediawiki/dbservers.php
