#!/usr/bin/php
<?php

$nodes = array();
$ret=0;
exec("relation-list",$nodes,$ret);
if ($ret)
{
  print "relation-list failed\n";
  exit($ret);
}

$dbservers = array();
foreach ($nodes as $node)
{
    $relout = popen("relation-get --format JSON - $node");
    $json = stream_get_contents($relout);
    $node = json_decode($json);
    $dbservers[] = array('host'=>$node->host,'dbname'=>$node->database,'user'=>$node->user,'password'=>$node->password,'type'=>'mysql'); 
}

file_put_contents('/etc/mediawiki/slaves.data', serialize($dbservers));
$home = dirname(__FILE__);
exec($home.'/combine-dbservers');
