#!/bin/bash

set -x

# Check if amulet is installed before addign repository and updating apt-get.
dpkg -s amulet
if [ $? -ne 0 ]; then
  sudo add-apt-repository -y ppa:juju/stable
  sudo apt-get update -qq
  sudo apt-get install -y amulet
fi
sudo apt-get install python3-pymysql
