#!/bin/bash
#
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed, modified, or broken
# This script should be idempotent.
#raw
echo $ENSEMBLE_REMOTE_UNIT modified its settings
echo Relation settings:
relation-get
echo Relation members:
relation-list
#end raw
