#!/usr/bin/env python

import os
import urllib
import subprocess
import json
import time

upload_path = "/var/www/wp-uploads"
config_file_path_template = "/etc/wordpress/config-%s.php"
hostname_url = "http://169.254.169.254/latest/meta-data/public-hostname"

def do(*args):
    print "do", args
    p = subprocess.Popen(args, close_fds=True)
    os.waitpid(p.pid, 0)

wordpress_template = """\
<?php
define('DB_NAME', '%(database)s');
define('DB_USER', '%(database_user)s');
define('DB_PASSWORD', '%(database_password)s');
define('DB_HOST', '%(database_host)s');
define('SECRET_KEY', '%(secret_key)s');

#This will disable the update notification.
define('WP_CORE_UPDATE', false);

$table_prefix  = 'wp_';
$server = '%(database_host)s';
$loginsql = '%(database_user)s';
$passsql = '%(database_password)s';
$base = '%(database)s';
$upload_path = '/var/www/wp-uploads/%(hostname)s';
$upload_url_path = 'http://%(hostname)s/wp-uploads';
?>
"""

apache_template = """\
<VirtualHost *:80>
  ServerName %(hostname)s
  DocumentRoot /var/www/%(hostname)s
  Options All
  ErrorLog /var/log/apache2/wp-error.log
  TransferLog /var/log/apache2/wp-access.log
  # Store uploads in /var/www/wp-uploads/$0
  RewriteEngine On
  RewriteRule ^/wp-uploads/(.*)$ /var/www/wp-uploads/%%{HTTP_HOST}/$1
</VirtualHost>
"""


def setup_wordpress():

    hostname = urllib.urlopen(hostname_url).read().strip()
    remote_unit = os.environ.get("ENSEMBLE_REMOTE_UNIT")

    print "remote unit", remote_unit

    # Check we haven't already been setup.
    if os.path.exists(config_file_path_template % hostname):
        print "Already Configured, Exiting"
        return

    p = subprocess.Popen(["relation-get", "--format", "json"],
                         stdout=subprocess.PIPE, close_fds=True)
    settings = json.loads(p.stdout.read().strip())

    print "Settings"
    import pprint
    pprint.pprint(settings)

    # Get the database settings
    database = settings.get("database")
    password = settings.get("password")
    user = settings.get("user")
    host = settings.get("host")

    # Ensure the remote unit has self configured.
    config = {
        "database_host": host,
        "database": database,
        "database_password": password,
        "database_user": user,
        "hostname": hostname,
        "secret_key": "wp"}

    # Verify we have all of our database settings.
    broken = False
    for k, v in config.items():
        if not v:
            print "Do not have for %r: %r" % (k, v)
            broken = True

    if broken:
        print "Could not fetch database settings, exiting."
        return

    # Setup appropriate upload paths and directories
    do("ln", "-s", "/usr/share/wordpress", "/var/www/%s" % hostname)

    do("mkdir", "-p", upload_path)
    do("mkdir", "-p", os.path.join(upload_path, hostname))
    do("chown", "-R", "root:www-data", upload_path)

    os.chmod(upload_path, 0744)
    os.chmod(os.path.join(upload_path, hostname), 0770)

    do("chown", "-R", "root:www-data", "/var/www/%s/wp-content" % hostname)
    do("chmod", "0644", "/etc/apache2/sites-available/%s" % hostname)

    # Write the wordpress config
    fh = open(config_file_path_template % hostname, "w")
    fh.write(wordpress_template % config)
    do("chmod", "0644", config_file_path_template % hostname)
    fh.close()

    # Write the apache config
    fh = open("/etc/apache2/sites-available/%s" % hostname, "w")
    fh.write(apache_template % config )
    fh.close()
    do("chmod", "0644", "/etc/apache2/sites-available/%s" % hostname)

    # Configure apache.
    do("a2enmod", "rewrite")
    do("a2enmod", "vhost_alias")
    do("a2ensite", hostname)

    # Restart apache
    do("/etc/init.d/apache2", "restart")

setup_wordpress()
