#!/bin/sh

case "$ENSEMBLE_CHANGE" in
joined|modified)

  IP=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'|head -n 1`

  echo setting ip to $IP

  relation-set ip=$IP port=80 hostname=`hostname -s`
  ;;
departed)
  ;;
*)
  echo unexpected change type $ENSEMBLE_CHANGE
  exit 1
esac
