#!/bin/bash
set -e

apt-get update

sudo apt-get install -y ruby1.9.1 ruby1.9.1-dev \
  rubygems1.9.1 irb1.9.1 ri1.9.1 rdoc1.9.1 \
  build-essential libopenssl-ruby1.9.1 libssl-dev zlib1g-dev

gem install bundler --no-rdoc --no-ri

cd "$(dirname $0)../cookbooks" && bundle install

mkdir -p /etc/chef

cat > /etc/chef/solo.rb <<EOF
cookbook_path '$CHARM_DIR/cookbooks'
EOF
