#!/bin/bash
set -e

HOOK_NAME=\$(basename \$0)
CHARM_NAME=$metadata.package

if [[ "\$HOOK_NAME" == *-relation-* ]]; then
  COOKBOOK_NAME="\${HOOK_NAME%-relation*}-relation"
  RECIPE_NAME=\${HOOK_NAME\#*relation-}
else
  COOKBOOK_NAME=\$CHARM_NAME
  RECIPE_NAME=\$HOOK_NAME
fi

cd "\$(dirname \$0)" && bundle exec chef-solo -o "recipe[\$COOKBOOK_NAME::\$RECIPE_NAME]"
