#!/bin/sh
set -ex
# Kill the replication
mysql -uroot -p`cat /var/lib/mysql/mysql.passwd` -e 'STOP SLAVE;'
mysql -uroot -p`cat /var/lib/mysql/mysql.passwd` -e 'RESET SLAVE;'
# No longer a slave
# XXX this may change the server-id .. not sure if thats what we
# want!
if [ -f /var/lib/juju/i.am.a.slave ]; then
  rm /var/lib/juju/i.am.a.slave
fi
