#!/bin/bash

export PATH=$SNAP/bin:$SNAP/usr/bin:$SNAP/libexec/git-core:$PATH
export GIT_TEMPLATE_DIR=$SNAP/share/git-core/templates
export UNIXCONFDIR=$SNAP/etc
export PREFIX=$SNAP
export GIT_EXEC_PATH=$SNAP/usr/lib/git-core
export LC_ALL=C.UTF-8

exec "$SNAP/bin/charm" "$@"
