#!/usr/bin/env python

import os
import sys
from launchpadlib.launchpad import Launchpad


def remote_charms():
    lp = Launchpad.login_anonymously('charm-tools', 'production',
                                     version='devel')
    charm = lp.distributions['charms']
    current_series = str(charm.current_series).split('/').pop()
    branches = charm.getBranchTips()
    charms = []

    for branch in branches:
        try:
            branch_series = str(branch[2][0]).split('/')[0]
            charm_name = str(branch[0]).split('/')[3]
        except IndexError:
            branch_series = ''
        if branch_series == current_series:
            charms.append("lp:charms/%s" % charm_name)
        else:
            charms.append("lp:%s" % branch[0])
    return charms


def local_charms(directory):
    return os.listdir(directory)

if __name__ == "__main__":
    if len(sys.argv) > 1:
        print('usage: list [ --help ]')
        if sys.argv[1] == '--help':
            sys.exit(0)
        else:
            sys.exit(1)

    print "\n".join(charms())
