#!/usr/bin/env python

from launchpadlib.launchpad import Launchpad
import sys

if len(sys.argv) > 1:
    print('usage: list [ --help ]')
    if sys.argv[1] == '--help':
        sys.exit(0)
    else:
        sys.exit(1)

lp = Launchpad.login_anonymously('charm-tools', 'production', version='devel')
charm = lp.distributions['charms']
current_series = str(charm.current_series).split('/').pop()
branches = charm.getBranchTips()

for branch in branches:
    try:
        branch_series = str(branch[2][0]).split('/')[0]
        charm_name = str(branch[0]).split('/')[3]
    except IndexError:
        branch_series = ''
    if branch_series == current_series:
        print "lp:charms/%s" % charm_name
    else:
        print "lp:%s" % branch[0]
