#!/bin/sh
home=`dirname $0`
charm_home=$1

if [ -z "$charm_home" ] ; then
    echo "usage: update charm_directory" >&2
    exit 1
fi

echo Pulling charm list from launchpad
newfile=`mktemp $charm_home/.mrconfig.XXXXXXXX`
cp /dev/null $newfile
for s in `$home/list | awk -F\/ '/^lp:charm\// { print $2 }'` ; do
    cat >> $newfile <<EOF
[$s]
checkout = bzr checkout lp:charm/$s $s

EOF
done
echo updating $charm_home/.mrconfig
mv -f $newfile $charm_home/.mrconfig
