name: charm
version: git
version-script: charmtools/git_version.py
summary: charm and charm-tools
description: charmstore-client and charm-tools
confinement: strict
grade: stable
apps:
  charm:
    command: env PATH=$SNAP/bin:$SNAP/usr/bin:$SNAP/libexec/git-core:$PATH GIT_TEMPLATE_DIR=$SNAP/share/git-core/templates UNIXCONFDIR=$SNAP/etc PREFIX=$SNAP GIT_EXEC_PATH=$SNAP/usr/lib/git-core LC_ALL=C.UTF-8 $SNAP/bin/charm
    plugs:
      - network
      - browser-support
      - home
      - removable-media
parts:
  charm:
    source: https://github.com/juju/charmstore-client.git
    source-tag: 2.2.3
    source-type: git
    plugin: godeps
    go-importpath: github.com/juju/charmstore-client
    build-packages:
      - bzr
  charm-tools:
    source: .
    plugin: python
    python-version: python3
    requirements: requirements.txt
    stage-packages:
      - git-core
      - libssl-dev
      - libffi-dev
      - python3
      - python3-setuptools
    stage:
      - -usr/share/doc*
      - -usr/share/lintian
      - -usr/share/git-web
      - -usr/share/man
      - -usr/share/perl*
      - -usr/share/pixmaps
    # work around python plugin forcibly excluding pip bins, even if they're
    # explicitly added to stage
    override-prime: |
      snapcraftctl prime
      cp $SNAPCRAFT_PART_INSTALL/bin/pip* bin/
  charm-version:
    source: snap/workarounds/
    plugin: dump
    stage:
      - charmstore-client-version
    after: [charm-tools]
