name: charm
version: git
version-script: charmtools/git_version.py
summary: charm and charm-tools
description: charmstore-client and charm-tools
confinement: strict
grade: stable
apps:
  charm:
    command: env PATH=$SNAP/bin:$SNAP/usr/bin:$SNAP/libexec/git-core:$PATH GIT_TEMPLATE_DIR=$SNAP/share/git-core/templates UNIXCONFDIR=$SNAP/etc PREFIX=$SNAP GIT_EXEC_PATH=$SNAP/usr/lib/git-core LC_ALL=C.UTF-8 $SNAP/bin/charm
    plugs:
      - network
      - browser-support
      - home
      - removable-media
parts:
  go:
    source-tag: go1.10.3
  charmstore-client:
    after: [go]
    source: https://github.com/juju/charmstore-client.git
    source-branch: master
    source-type: git
    plugin: godeps
    go-importpath: github.com/juju/charmstore-client
    build-packages:
      - bzr
  charm-tools:
    source: .
    plugin: python
    python-version: python3
    requirements: requirements.txt
    stage-packages:
      - git-core
      - libssl-dev
      - libffi-dev
      - python3
      - python3-setuptools
    stage:
      - -usr/share/doc*
      - -usr/share/lintian
      - -usr/share/git-web
      - -usr/share/man
      - -usr/share/perl*
      - -usr/share/pixmaps
      # exclude the embedded pip, so we can replace it
      - -lib/python*/site-packages/virtualenv_support/pip-*.whl
    # Work around python plugin forcibly excluding pip bins, even if they're
    # explicitly added to stage.  Also forcibly update the pip embedded in
    # virtualenv to get the lsb_release fix that was released with pip 10.
    override-prime: |
      snapcraftctl prime
      cp $SNAPCRAFT_PART_INSTALL/bin/pip* bin/
      pip download pip -d lib/python*/site-packages/virtualenv_support/
  charm-version:
    source: snap/workarounds/
    plugin: dump
    override-stage: |
      snapcraftctl stage
      ../parts/charm-tools/build/charmtools/git_version.py --build-charm-version
    after: [charm-tools]
