name: charm
version: git
version-script: charmtools/git_version.py
summary: charm and charm-tools
description: charmstore-client and charm-tools
confinement: classic
grade: stable
base: core18
apps:
  charm:
    command: bin/wrappers/charm
parts:
  charmstore-client:
    build-attributes: ['no-patchelf']
    source: https://github.com/juju/charmstore-client.git
    source-branch: master
    source-type: git
    plugin: godeps
    go-importpath: github.com/juju/charmstore-client
    build-packages:
      - bzr
  bhttp:
    plugin: godeps
    build-attributes: ['no-patchelf']
    source: https://github.com/rogpeppe/bhttp
    source-branch: master
    source-type: git
    go-importpath: github.com/rogpeppe/bhttp
  charm-tools:
    source: .
    plugin: python
    python-version: python3
    requirements:
      - requirements.txt
    stage-packages:
      - git-core
      - libssl-dev
      - libffi-dev
      - python3
      - python3-setuptools
    stage:
      - -usr/share/doc*
      - -usr/share/lintian
      - -usr/share/git-web
      - -usr/share/man
      - -usr/share/perl*
      - -usr/share/pixmaps
      # exclude the embedded pip, so we can replace it
      - -lib/python*/site-packages/virtualenv_support/pip-*.whl
    # Work around python plugin forcibly excluding pip bins, even if they're
    # explicitly added to stage.  Also forcibly update the pip embedded in
    # virtualenv to get the lsb_release fix that was released with pip 10.
    override-prime: |
      snapcraftctl prime
      cp $SNAPCRAFT_PART_INSTALL/bin/pip* bin/
      pip download pip -d lib/python*/site-packages/virtualenv_support/
  versions:
    after: [charmstore-client, charm-tools]
    plugin: dump
    source: .
    build-packages:
      - python-pip
    override-build: |
      pip install vergit
      vergit --format=json ../../charm-tools/src > $SNAPCRAFT_PART_INSTALL/charm-tools-version
      vergit --format=json ../../charmstore-client/src > $SNAPCRAFT_PART_INSTALL/charmstore-client-version
    stage:
      - charm-tools-version
      - charmstore-client-version
    prime:
      - charm-tools-version
      - charmstore-client-version
  wrappers:
    plugin: dump
    source: helpers/snap-wrappers/
    organize:
      '*': bin/wrappers/
