#!/usr/bin/env python

from common import get_db_cursor, database_name, user

import urllib
import subprocess
import os
import string
import random

cursor = get_db_cursor()

# Find existing databases
cursor.execute("show databases")
databases = [i[0] for i in cursor.fetchall()]

# Determine if we need to create a new database
if database_name not in databases:
  # Create new database
  cursor.execute(
      "create database `%s` character set utf8" % database_name)

# Create database user and grant access
service_password = "".join(random.sample(string.letters, 10))
cursor.execute(
    "grant all on `%s`.* to `%s` identified by '%s'" % (
        database_name,
        user,
        service_password))

cursor.execute("flush privileges")

cursor.close()

hostname = urllib.urlopen(
    "http://169.254.169.254/latest/meta-data/local-hostname").read()

print "setting values"
print "host", hostname
print "database", database_name
print "user", user
print "password", service_password


print str(["relation-set",
 "database=%s" % database_name,
 "user=%s" % user,
 "password=%s" % service_password,
 'host=%s' % hostname,])

# Store new values in relation settings.
p = subprocess.Popen(
    ["relation-set",
     "database=%s" % database_name,
     "user=%s" % user,
     "password=%s" % service_password,
     'host=%s' % hostname,],
    close_fds = True)

os.waitpid(p.pid, 0)
