#!/bin/bash

sudo apt-get install -qqy debconf-utils python-mysqldb uuid augeas-tools augeas-lenses

PASSFILE=/var/lib/ensemble/mysql.passwd 
if ! [ -f $PASSFILE ] ; then
  uuid > $PASSFILE
fi
PASSWORD=`cat $PASSFILE`

echo mysql-server-5.1 mysql-server/root_password password $PASSWORD | debconf-set-selections
echo mysql-server-5.1 mysql-server/root_password_again password $PASSWORD | debconf-set-selections

DEBIAN_FRONTEND=noninteractive apt-get -y install -qq mysql-server

unit_id=`echo $ENSEMBLE_UNIT_NAME | cut -d/ -f2`

# augeas 0.8.0 and later knows about my.cnf format .. otherwise use ours
augvers=`dpkg -l augeas-lenses|awk '/^ii/ {print $3}'`
if dpkg --compare-versions $augvers '<' 0.8.0 || \
  ! [ -f /usr/share/augeas/dist/mysql.aug ] ; then
  echo augeas $augvers needs mysql.aug and inifile.aug file from formula...
  mv -f /usr/share/augeas/lenses/dist/inifile.aug /var/backups
  cp -v `dirname $0`/../inifile.aug /usr/share/augeas/lenses/dist
  cp -v `dirname $0`/../mysql.aug /usr/share/augeas/lenses/dist
else
  echo using mysql.aug from $augvers
fi
augtool <<EOF
defnode mysqld '/files/etc/mysql/my.cnf/target[. = "mysqld"]'
set \$mysqld/server_id $unit_id
set \$mysqld/log_bin /var/log/mysql/mysql-bin.log
set \$mysqld/default_storage_engine InnoDB
save
EOF

service mysql stop || :
service mysql start
