#!/bin/sh -e
#
# Master side of master/slave replication

ROOTARGS="-uroot -p`cat /var/lib/ensemble/mysql.passwd`"
snapdir=/var/www/snaps
mkdir -p $snapdir
apt-get -y install apache2
# disable wide-open access (restrict to each db IP)
allowline=`augtool get /files/etc/apache2/sites-available/default/VirtualHost/Directory[2]/directive[4]/arg[2]`
if [ "$allowline" = "/files/etc/apache2/sites-available/default/VirtualHost/Directory[2]/directive[4]/arg[2] = all" ] ; then
  # disable allow from all
  augtool -b <<EOF
  defvar webroot /files/etc/apache2/sites-available/default/VirtualHost/Directory[2]
  rm \$webroot/directive[4]
  save
EOF
  service apache2 reload
fi
# TODO: settings.. make mmin tunable as it is highly subjective
recent_backup=`find $snapdir -name 'replication_seed.*.sql.gz' -mmin -60|head -1`
if [ -z "$recent_backup" ] ; then
    recent_backup=replication_seed.`date +%Y%m%d%H%M%S`.sql.gz
    echo `date`: Creating snapshot $recent_backup
    mysqldump $ROOTARGS --all-databases --single-transaction --master-data |gzip>$snapdir/$recent_backup
fi

case $ENSEMBLE_CHANGE in
joined)
  ;;
modified)
  remote_ip=`relation-get ip`
  local_ip=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'|head -n 1`
  augtool -b <<EOF
  defvar webroot /files/etc/apache2/sites-available/default/VirtualHost/Directory[2]
  set \$webroot/directive[last()+1] allow
  set \$webroot/directive[last()]/arg from
  set \$webroot/directive[last()]/arg $remote_ip/32
  save
EOF
  service apache2 reload
  mysql $ROOTARGS -e "GRANT REPLICATION_CLIENT ON *.* TO \`$ENSEMBLE_REMOTE_UNIT\`@\`$remote_ip\` IDENTIFIED BY '$pass'"
  relation-set dumpurl=/snaps/$name \
                       user=$ENSEMBLE_REMOTE_UNIT \
                       password=$pass \
                       ip=$local_ip
                       port=3306
  ;;
departed)
  remote_ip=`relation-get ip`
  mysql $ROOTARGS -e "REVOKE PRIVILEGES ON *.* FROM `$ENSEMBLE_REMOTE_UNIT`@`$remote_ip`"
  # find allow lines
  for aline in `augtool ls /files/etc/apache2/sites-available/default/VirtualHost/Directory[2]|grep " = allow"|cut -d' ' -f1` ; do
    ip=`augtool get /files/etc/apache2/sites-available/default/VirtualHost/Directory[2]/$aline/arg[2]`
    if [ "$ip" = "$remote_ip/32" ] ; then
      echo -e "rm /files/etc/apache2/sites-available/default/VirtualHost/Directory[2]/$aline\nsave" | augtool -b
      echo removed $aline from /files/etc/apache2/sites-available/default/VirtualHost/Directory[2]
      service apache2 reload
      break
    fi
  done
  ;;
*)
  exit 0
  ;;
esac
